Update action to node version 16 (#123)

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -3,7 +3,7 @@
 # `index.js` is the code that will run.
 # For our project, we generate this file through a build process from other source files.
 # We need to make sure the checked-in `index.js` actually matches what we expect it to be.
-name: Check dist/
+name: Check update compatibility
 
 on:
   push:
@@ -24,23 +24,24 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Set Node.js 16.x
-        uses: actions/setup-node@v3.3.0
+        uses: actions/setup-node@v3
         with:
-          node-version: 16.x
+          node-version: 16.x # if possible should use `lts/*`
+          cache: 'npm'
 
       - name: Install dependencies
         run: npm ci
 
-      - name: npm run build
+      - name: Build lib
         run: npm run build
 
-      - name: check for uncommitted changes
-        # Ensure no changes.
+      - name: Check Update compatiility with `dist/index.js`
+        # Ensure no changes with `dist/index.js`.
         run: |
           git add -u . # compare after applying git EOL normalization
           git diff --cached --exit-code --stat \
-          || (echo "##[error] found changed files after build. please 'yarn run build'" \
-                  "and check in all changes" \
+          || (echo "##[error] found changed files after build in CI." \
+                  "Please 'yarn run build' locally and check in all changes" \
               && git diff --cached \
               && exit 1)
 
@@ -59,6 +60,7 @@ jobs:
       with:
         stablePackages: true
         previewPackages: true
+  
     - name: nanodu failing repos and solutions options
       uses: ./
       continue-on-error: true
