Initial version

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -23,31 +23,48 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set Node.js 12.x
-        uses: actions/setup-node@v2.5.1
+      - name: Set Node.js 16.x
+        uses: actions/setup-node@v2
         with:
-          node-version: 12.x
+          node-version: 16.x
 
       - name: Install dependencies
         run: npm ci
 
-      - name: Rebuild the dist/ directory
-        run: |
-          npm run build
-          npm run package
+      - name: yarn
+        run: yarn
 
-      - name: Compare the expected and actual dist/ directories
-        run: |
-          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build.  See status below:"
-            git diff
-            exit 1
-          fi
-        id: diff
+      - name: yarn run build
+        run: yarn run build
 
-      # If index.js was different than expected, upload the expected version as an artifact
-      - uses: actions/upload-artifact@v2
-        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
-        with:
-          name: dist
-          path: dist/
+      - name: check for uncommitted changes
+        # Ensure no changes.
+        run: |
+          git add -u . # compare after applying git EOL normalization
+          git diff --cached --exit-code --stat \
+          || (echo "##[error] found changed files after build. please 'yarn run build'" \
+                  "and check in all changes" \
+              && git diff --cached \
+              && exit 1)
+
+  test:
+    runs-on: ubuntu-latest
+    needs: check-dist
+    steps:
+
+    - uses: actions/checkout@v1
+      with:
+        ref: 'main' 
+
+    - name: nanodu failing packages options
+      uses: ./
+      continue-on-error: true
+      with:
+        stablePackages: true
+        previewPackages: true
+    - name: nanodu failing repos and solutions options
+      uses: ./
+      continue-on-error: true
+      with:
+        solutionsToCheck: ''
+        reposToUpdate: ''
